export const sectorOptions = [
  "Yazılım ve Bilişim",
  "Yapay Zeka ve Veri",
  "Fintek",
  "Sağlık Teknolojileri",
  "Eğitim Teknolojileri",
  "Tarım ve Gıda Teknolojileri",
  "Enerji ve Çevre Teknolojileri",
  "E-ticaret ve Perakende",
  "Oyun ve Eğlence",
  "Medya ve İletişim",
  "Turizm",
  "Lojistik ve Ulaşım",
  "Üretim ve Endüstri",
  "Savunma ve Havacılık",
  "Gayrimenkul ve İnşaat",
  "Sosyal Girişim",
  "Diğer",
] as const;
